name: .NetCore app to an IIS server

env:
  ROOT_PATH: './HelloWorldApp.web'     
  DOTNET_VERSION: '8.0'  # set this to the .NET Core version to use

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build and deploy with dotnet
        run: |
          dotnet build --configuration Release ${{ env.ROOT_PATH }}
          dotnet publish -c Release -o ${{ runner.workspace }}/myapp ${{ env.ROOT_PATH }}

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{ runner.workspace }}/myapp

      - name: Download artifact for deployment
        uses: actions/download-artifact@v2
        with:
          name: .net-app
          path: ${{ runner.workspace }}/downloaded-myapp

      # Add deployment steps using the downloaded artifacts as needed.
